parameters:
    database_driver: pdo_mysql
    database_host: localhost
    database_port: null
    database_name: gestionDeFlotteBdd
    database_user: root
    database_password: null
    mailer_transport: smtp
    mailer_host: localhost
    mailer_user: null
    mailer_password: null
    locale: en
    secret: 0b33ca47bb458b1a97fe54598a08ed67408cc104
    database_path: null
